### ISSUE TITLE
Create Entities for K8S Custom Resources

### ISSUE THREAD

**Issue by tobias-bahls** [zalando-zmon/zmon-agent-core#88]
If one wants to write a check e.g. to monitor etcd clusters deployed with [etcd-operator](https://github.com/coreos/etcd-operator), it would be handy to have the actual custom resources as entities in ZMON. 

In the case of `etcd-operator`, the K8S entity even exposes some health-metrics that could be very useful in a check, e.g:

```
status:
  clientPort: 2379
  conditions:
  - lastTransitionTime: 2018-12-03T09:38:46Z
    lastUpdateTime: 2018-12-03T09:38:46Z
    reason: Cluster available
    status: "True"
    type: Available
  currentVersion: 3.3.10
  members:
    ready:
    - etcd-cluster-2z4b5scjgp
    - etcd-cluster-4qltzm25xr
    - etcd-cluster-r6nw5mc9hg
    - etcd-cluster-szgbpl7zdk
    - etcd-cluster-wktt76nszx
  phase: Running
  serviceName: etcd-cluster-client
  size: 5
  targetVersion: ""
```
